
# Strategy Card Exceptions
class StrategyCardException(Exception): ...
class StrategyCardInitException(StrategyCardException): ...
class DiplomacyPrimaryAbilityException(StrategyCardException): ...
class DiplomacySecondaryAbilityException(StrategyCardException): ...

# Exhaustables
class ExhaustableAlreadyExhausted(Exception): ...